### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by 1997MarsRover** [tairov/llama2.mojo#68]
Stumbled on this while trying to run the code on WSL Ubuntu
```yaml
num parallel workers: 2  SIMD width: 16
checkpoint size:  60816028 [ 57 MB ] | n layers: 6 | vocab size: 32000
terminate called after throwing an instance of 'std::system_error'
  what():  Resource temporarily unavailable
```
